// 경로: src/styles/components/recordComponent.styles.ts
import { StyleSheet } from 'react-native';
import { Theme } from '../../types/theme';

export const createStyles = (theme: Theme) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.background,
        padding: 16,
    },
    accountCard: {
        backgroundColor: theme.colors.card,
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    accountHeader: {
        flexDirection: 'row',
        marginBottom: 12,
        alignItems: 'flex-end',
    },
    accountCompanay: {
        fontSize: 16,
        fontWeight: 'bold',
        paddingRight: 5,
        color: theme.colors.text,
    },
    accountNumber: {
        fontSize: 14,
        fontWeight: 'bold',
        color: theme.colors.text,
    },
    infoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    infoLabel: {
        fontSize: 14,
        color: theme.colors.placeholder,
    },
    infoValue: {
        fontSize: 14,
        fontWeight: '500',
        color: theme.colors.text,
    },
    positiveValue: {
        color: theme.colors.positive,
    },
    negativeValue: {
        color: theme.colors.negative,
    },
    tableHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border,
        marginTop: 8,
    },
    headerText: {
        fontSize: 13,
        fontWeight: '500',
        color: theme.colors.placeholder,
        flex: 1,
        textAlign: 'center',
    },
    recordRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border,
    },
    recordName: {
        fontSize: 13,
        flex: 1,
        paddingRight: 8,
        color: theme.colors.text,
    },
    recordDate: {
        fontSize: 13,
        color: theme.colors.placeholder,
        flex: 1,
        textAlign: 'center',
    },
    recordProfit: {
        fontSize: 13,
        fontWeight: '500',
        flex: 1,
        textAlign: 'right',
        color: theme.colors.text,
    },
    selectedRecord: {
        backgroundColor: theme.colors.primary + '20', // 투명도 20% 적용
    },
    recordDetail: {
        marginTop: 16,
        padding: 16,
        backgroundColor: theme.colors.card,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.primary,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    recordDetailTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: theme.colors.text,
    },
    recordDetailHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border,
    },
    closeButton: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: theme.colors.placeholder + '20',
        justifyContent: 'center',
        alignItems: 'center',
    },
    closeButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: theme.colors.placeholder,
    },
    detailSection: {
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 12,
        paddingBottom: 4,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border,
    },
    detailInfoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 6,
    },
    detailLabel: {
        fontSize: 14,
        color: theme.colors.placeholder,
        fontWeight: '500',
    },
    detailValue: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.text,
        textAlign: 'right',
        flex: 1,
        marginLeft: 16,
    },
    assetRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 12,
        marginBottom: 6,
        backgroundColor: theme.colors.background,
        borderRadius: 8,
    },
    assetInfo: {
        flex: 1,
    },
    assetName: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.text,
        marginBottom: 2,
    },
    assetDetails: {
        fontSize: 12,
        color: theme.colors.placeholder,
    },
    assetValues: {
        alignItems: 'flex-end',
    },
    assetWeight: {
        fontSize: 12,
        fontWeight: '500',
        color: theme.colors.primary,
        marginBottom: 2,
    },
    assetReturn: {
        fontSize: 12,
        fontWeight: '500',
        marginBottom: 2,
    },
    assetAmount: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.text,
    },
    chartContainer: {
        backgroundColor: theme.colors.background,
        borderRadius: 8,
        padding: 12,
    },
    chartRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    chartLabel: {
        fontSize: 12,
        fontWeight: '500',
        color: theme.colors.text,
        width: 80,
        marginRight: 12,
    },
    chartBarContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        height: 20,
        backgroundColor: theme.colors.card,
        borderRadius: 10,
        position: 'relative',
    },
    chartBar: {
        height: 20,
        borderRadius: 10,
        minWidth: 4,
    },
    chartPercentage: {
        position: 'absolute',
        right: 8,
        fontSize: 10,
        fontWeight: 'bold',
        color: theme.colors.text,
    },
    actionButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 16,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: theme.colors.border,
    },
    actionButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 8,
        marginHorizontal: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    actionButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#FFFFFF',
    },
});
